roots = ["ReplicatedStorage/myTests", "ServerStorage/some/other/tests"] # locations of your .spec files (which are found as descendants too)
extraOptions = {} # optional extraOptions for TestBootstrap